#includes = ["include.toml"]

[hi.tab]
name = "HI!"

[hi.echo_hi]
name = "echo hi"
command = "echo hi"
icon = "tabber.png"
icon_subsample = [4,4]

[hi.echo_hello]
name = "echo hello"
command = "echo hello"

[hello.tab]
name = "HELLO!"

[hello.echo_hello]
name = "echo hello"
command = "echo hello"

[hello.echo_hi]
name = "echo hi"
command = "echo hi"
