includes = ["include.toml"]

[hi]
name = "HI!"

[hi.echo_hi]
command = "echo hi"

[hi.sleep]
name = "sleep for 1 second"
command = "sleep 1s"
show_status = true

[hello.echo_hello]
name = "echo hello"
command = "echo hello"

[hello.echo_hi]
name = "echo hi"
command = "echo hi"
