includes = ["include.toml"]

[hi.tab]
name = "HI!"

[hi.echo_hi]
name = "echo hi"
command = "echo hi"

[hi.echo_hello]
name = "sleep for 10 seconds"
command = "sleep 10s"

[hello.tab]
name = "HELLO!"

[hello.echo_hello]
name = "echo hello"
command = "echo hello"

[hello.echo_hi]
name = "echo hi"
command = "echo hi"
